### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by LuAmRaTeu** [stg7/ctag#1]
Is it possible to implement pdf support?
would be nice

**Comment by stg7** [comment]
PDF as input or as output?

output is easy possible via inkscape.

for input I would add another tool in the pipeline for extraction of plain text, because only with e.g. tika (java project) text extract is somehow possible from pdf

**Comment by stg7** [comment]
I added some scripts and infos for input and output of pdfs, see:
https://github.com/stg7/ctag/commit/a9cbf329124bcc905aea36f479c51cd7e5d80c6c

**Comment by stg7** [comment]
you can also look at my current rewrite and optimization branch https://github.com/stg7/ctag/commit/7ebe475bc617910e4bde5167be969331b542ea92
